# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=500']

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: 1.15.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.1.0]
    exclude: README.md

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args:
    - --profile=black

- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
    - id: pyupgrade
      args: [--py38-plus]

- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.0
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
        - --expand-star-imports
        - --ignore-init-module-imports

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0  # pick a git hash / tag to point to
  hooks:
  - id: pydocstyle
    files: ^src/sparselm/
    args:
      - --convention=google
      - --add-ignore=D107

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
