name: lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: flake8
        run: |
            flake8 --version
            flake8 --count --show-source --statistics src/sparselm
            # exit-zero treats all errors as warnings.
            flake8 --count --exit-zero --max-complexity=20 --statistics src/sparselm
      - name: black
        run: |
          black --version
          black --check --diff --color src/sparselm
      - name: pydocstyle
        run: |
          pydocstyle --version
          pydocstyle --count src/sparselm
      # Not in shape for this yet
      # - name: pylint
      #  run: |
      #     pylint sparselm
      #- name: mypy
       #   run: |
        #    mypy --version
         #   rm -rf .mypy_cache
          #  mypy sparselm
