name: release

on:
  release:
    types: [published]
    inputs:
      release-pypi:
        required: true
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      release-pypi:
        required: true
        type: boolean
        description: "if true a release is made on PyPI"

jobs:
  test:
    uses: sparselm/sparselm/.github/workflows/test.yml@main

  build:
    needs: test
    uses: sparselm/sparselm/.github/workflows/build.yml@main

  release-docs:
    needs: test
    uses: sparselm/sparselm/.github/workflows/docs.yml@main

  release-pypi:
    needs: [build, docs]
    runs-on: ubuntu-latest
    if: github.event.inputs.release-pypi == 'true'

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
