name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        python_version: ["3.8", "3.9", "3.10"]  #  cvxopt install in python "3.11" fails

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install .[tests,dev]

      - name: Test with pytest
        run: |
          pytest tests --cov=sparselm --cov-report=xml

      - if: ${{ matrix.python_version == 3.9 && github.event_name == 'push' }}
        name: codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            coverage-reports: coverage.xml
