name: test

env:
  scip-version: 8.0.0

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 10
      matrix:
        python_version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          wget --quiet --no-check-certificate https://scipopt.org/download/release/SCIPOptSuite-${{ env.scip-version }}-Linux-ubuntu.deb
          sudo apt-get update && sudo apt install -y ./SCIPOptSuite-${{ env.scip-version }}-Linux-ubuntu.deb

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version:  ${{ matrix.python_version }}

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install .[tests,dev]

      - name: Test with pytest
        run: |
          pytest tests --cov=sparselm --cov-report=xml

      - if: ${{ matrix.python_version == 3.11 && github.event_name == 'push' }}
        name: codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
            project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            coverage-reports: coverage.xml
